### ISSUE TITLE
Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again

### ISSUE THREAD

**Issue by oscarvarto** [cescoffier/reactive-systems-in-java#130]
Hi!

I tried running `mvn quarkus:dev` (or `quarkus dev`) in chapter 2 folder, but I am getting the following error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:138)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:145)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:97)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
        ... 1 more
Caused by: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
        at io.quarkus.deployment.dev.IsolatedDevModeMain.close(IsolatedDevModeMain.java:367)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:512)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:142)
        ... 3 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I am using an Arch Linux variant (Garuda) with Java 11.0.15. Any ideas/pointers to solve this?

**Comment by cescoffier** [comment]
Are you trying to update the version of quarkus while the dev mode is running? You need to stop the dev mode for that.

**Comment by oscarvarto** [comment]
@cescoffier Thanks for replying.

> Are you trying to update the version of quarkus while the dev mode is running?
No, I just execute `mvn quarkus:dev` nothing else.

**Comment by cescoffier** [comment]
Try with `clean` (`mvn clean quarkus:dev`) but I don't see any reason to have this behavior. As I said, this happens when you try to update the quarkus core version while running the application in dev mode.

**Comment by oscarvarto** [comment]
I get the same error/behavior with `clean`.

**Comment by kenfinnigan** [comment]
Is there another Quarkus application running at the same time?

Seems like a very odd error

**Comment by rafaeltuelho** [comment]
Hit the same issue today 🤔 
Any workaround?

**Comment by rafaeltuelho** [comment]
ok. Upgrading Quarkus Platform from `2.7.5.Final` to `2.15.1.Final` seems to solve this odd issue.

**Comment by adietish** [comment]
I can confirm this. Currently in pom `<quarkus-plugin.version>` and `<quarkus.platform.version>` point to different versions which is causing it. Having both consistent (ex. set to `2.8.2.Final` or latest stable `2.16.4.Final`) fixes it.
The dependabot obviously bumped to different versions.

**Comment by Ludocius** [comment]
Thank you, it worked out
<img width="714" alt="image" src="https://github.com/cescoffier/reactive-systems-in-java/assets/59232095/92eea7fe-bffd-4b4b-9456-2efff69b1b60">
